version: "3"
services:
  node-app:
    # container_name: node-express-app-container
    image: ghusnmhsen/codemesh
    # ports:
    #   - "4000:4000"
    depends_on:
      - mongo
      - redis
      - postgres
    deploy:
      replicas: 4
      placement:
        max_replicas_per_node: 1

      update_config:
        parallelism: 2
        delay: 10s

      restart_policy:
        condition: on-failure
        delay: 5s
  mongo:
    image: mongo
    container_name: mongodb-container
    volumes:
      - mongo-db:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

  postgres:
    image: postgres
    container_name: postgres-container
    volumes:
      - postgres-db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"
    restart: always

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app

volumes:
  mongo-db:
  postgres-db:
